title: N30 Files
description: >
  N30's publicly shared work.
baseurl: "" # Leave this blank for root-level deployment.
url: "https://n30dyn4m1c.github.io"
theme: jekyll-theme-minimal

# Permalink structure for blog posts
permalink: /:categories/:year/:month/:day/:title/
